### ISSUE TITLE
运行报错，日志在下面。能帮忙看看吗？

### ISSUE THREAD

**Issue by Kbstsn** [github123666/gonxueyun#2]
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 640, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.moguding.net', port=9000): Max retries exceeded with url: /session/user/v3/login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f824b4b8a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```

**Comment by github123666** [comment]
服务器ip被拉黑了
